import Head from 'next/head'
import Image from 'next/image'
import HomePage from '../src/Components/HomePage/HomePage'
import styles from '../styles/Home.module.css'

import imageHeader from '/public/assets/home/mobile/imageHeader.jpg'
export default function Home() {
  return (
    <div className='w-full h-screen'>
      <head>
        <title>Audiophile_ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />        
      </head>

      <div>
        <HomePage />
      </div>
      
    </div>
  )
}
